# Generated by Django 6.1 on 2026-08-15 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_notify_email_updates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notify_installation_complete',
        ),
    ]
