# Generated by Django 5.2.17 on 2026-08-30 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('TICKET_ASSIGNED', 'Ticket Assigned'), ('ASSESSMENT_SUBMITTED', 'Assessment Submitted'), ('TICKET_DECISION', 'Ticket Decision'), ('ADMIN_REVIEW_READY', 'Ready for Admin Review'), ('TICKET_APPROVED', 'Ticket Approved'), ('TICKET_RETURNED', 'Returned for Revision'), ('FEEDBACK_SUBMITTED', 'Feedback Submitted'), ('WORKER_ACCOUNT', 'Worker Account Change')], max_length=30)),
                ('message', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
