# Generated by Django 5.2.17 on 2026-08-09 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_address', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('preferred_date', models.DateField()),
                ('solar_package', models.CharField(max_length=100)),
                ('system_type', models.CharField(blank=True, choices=[('ON_GRID', 'On Grid'), ('HYBRID', 'Hybrid')], max_length=20)),
                ('status', models.CharField(choices=[('REQUEST_SUBMITTED', 'Request Submitted'), ('PI_ASSIGNED', 'Partner Installer Assigned'), ('ASSESSMENT_SUBMITTED', 'Assessment Submitted'), ('STAFF_REVIEW', 'Staff Review'), ('ADMIN_REVIEW', 'Admin Review'), ('APPROVED', 'Approved'), ('NC_CANNOT_PROCEED', 'Not Compatible - Cannot Proceed'), ('NC_CAN_REAPPLY', 'Not Compatible - Can Reapply'), ('WITHDRAWN', 'Withdrawn'), ('COMPLETED', 'Completed')], default='REQUEST_SUBMITTED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('partner_installer', models.ForeignKey(blank=True, limit_choices_to={'role': 'PARTNER_INSTALLER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
