# Generated by Django 5.2.17 on 2026-08-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='visit_date',
            field=models.DateField(blank=True, help_text='Actual scheduled visit date, set by Staff when assigning a Partner Installer.', null=True),
        ),
    ]
