# Generated by Django 6.1 on 2026-08-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_visit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='admin_revision_notes',
            field=models.TextField(blank=True, help_text="Admin's notes explaining why a ticket was sent back to Staff for revision.", null=True),
        ),
    ]
