# Generated by Django 6.1 on 2026-08-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_admin_revision_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
