# Generated by Django 5.2.17 on 2026-08-30 10:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalsheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='highlights',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PROFESSIONAL_TEAM', 'Professional Team'), ('ON_TIME', 'On-Time'), ('CLEAN_INSTALLATION', 'Clean Installation'), ('QUALITY_MATERIALS', 'Quality Materials'), ('FRIENDLY_STAFF', 'Friendly Staff'), ('FAST_INSTALLATION', 'Fast Installation')], max_length=30), blank=True, default=list, size=None),
        ),
    ]
