# Generated by Django 5.2.17 on 2026-08-09 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_roof_area_sqm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('roof_type', models.CharField(choices=[('CONCRETE', 'Concrete'), ('METAL', 'Metal'), ('SHINGLE', 'Shingle'), ('TILE', 'Tile'), ('OTHER', 'Other')], max_length=20)),
                ('roof_condition', models.CharField(choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=10)),
                ('recommended_package', models.CharField(max_length=100)),
                ('recommended_system_type', models.CharField(choices=[('ON_GRID', 'On Grid'), ('HYBRID', 'Hybrid')], max_length=20)),
                ('rated_capacity_kw', models.DecimalField(decimal_places=2, max_digits=6)),
                ('number_of_solar_panels', models.PositiveIntegerField()),
                ('inverter_size_kw', models.DecimalField(decimal_places=2, max_digits=6)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='ProofOfVisitPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='proof_of_visit/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='assessments.assessment')),
            ],
        ),
    ]
