# Generated by Django 5.2.17 on 2026-08-09 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Payment Terms',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rated_capacity_kw', models.DecimalField(decimal_places=2, max_digits=6)),
                ('system_type', models.CharField(choices=[('ON_GRID', 'On Grid'), ('HYBRID', 'Hybrid')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Price History',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_type', models.CharField(choices=[('INITIAL', 'Initial Quotation'), ('UPDATED', 'Updated Quotation')], max_length=10)),
                ('package_details', models.CharField(max_length=255)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('payment_terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='pricing.paymentterms')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
