# Generated by Django 6.1 on 2026-08-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('subject', models.CharField(choices=[('ROOF_ASSESSMENT', 'I want to request a roof assessment'), ('PACKAGE_QUESTION', 'I have a question about solar packages'), ('OTHER', 'Other concern')], max_length=20)),
                ('message', models.TextField()),
                ('is_replied', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-received_at'],
            },
        ),
    ]
