# Generated by Django 6.1 on 2026-08-16 18:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_inquiry_access_token_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='quotation_estimated_cost',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='quotation_message_to_customer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='quotation_package_details',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='quotation_payment_terms',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='quotation_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='quotation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='access_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
