# Generated by Django 6.1 on 2026-08-18 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_inquiry_quotation_estimated_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='access_token',
        ),
    ]
