# Generated by Django 6.1 on 2026-08-25 10:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0006_populate_access_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='access_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
